# Generated by Django 3.2.6 on 2021-10-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='timeindb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardcode', models.CharField(max_length=20)),
                ('vehicle', models.CharField(max_length=20)),
                ('plate', models.CharField(max_length=20)),
                ('timein', models.DateTimeField()),
                ('operator', models.CharField(max_length=50)),
                ('pic', models.CharField(max_length=500)),
                ('pic2', models.CharField(max_length=500)),
                ('lane', models.CharField(max_length=50)),
                ('pc', models.CharField(max_length=50)),
            ],
        ),
    ]
