# Generated by Django 3.2.6 on 2021-10-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoexit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeindb',
            name='timein',
            field=models.DateTimeField(null=True),
        ),
    ]
