# Generated by Django 3.2.6 on 2021-10-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoexit', '0002_alter_timeindb_timein'),
    ]

    operations = [
        migrations.CreateModel(
            name='scanned_qr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.CharField(max_length=500)),
                ('time_scanned', models.DateTimeField(null=True)),
            ],
        ),
    ]
